from typing import Protocol
from primp import AsyncClient
from eth_account import Account

from src.model.onchain.web3_custom import Web3Custom
from src.utils.config import Config


class KiteAIProtocol(Protocol):
    """Protocol class for KiteAI type hints to avoid circular imports"""

    account_index: int
    session: AsyncClient
    web3: Web3Custom
    config: Config
    wallet: Account
    discord_token: str
    twitter_token: str
    proxy: str

    # Инициализируем сервисы        
    kiteai_login_token: str = ""
    kiteai_signin_token: str = ""

    async def get_account_info(self) -> dict | None: ...
    async def connect_socials(self) -> bool: ...


# Account Factory ABI
ACCOUNT_FACTORY_ABI = [
    {
        "type": "function",
        "name": "getAddress",
        "stateMutability": "view",
        "inputs": [
            {"name": "owner", "type": "address", "internalType": "address"},
            {"name": "salt", "type": "uint256", "internalType": "uint256"},
        ],
        "outputs": [{"name": "addr", "type": "address", "internalType": "address"}],
    },
    {
        "type": "function",
        "name": "createAccount",
        "stateMutability": "nonpayable",
        "inputs": [
            {"name": "owner", "type": "address", "internalType": "address"},
            {"name": "salt", "type": "uint256", "internalType": "uint256"},
        ],
        "outputs": [{"name": "account", "type": "address", "internalType": "address"}],
    },
]

# Contract addresses
ACCOUNT_FACTORY_ADDRESS = "0x948f52524Bdf595b439e7ca78620A8f843612df3"

# Salt for account creation
SALT = "0x4b6f5b36bb7706150b17e2eecb6e602b1b90b94a4bf355df57466626a5cb897b"


STAKE_CONTRACT_ADDRESSES = {
    "Kite": "0x233b43fbe16b3c29df03914bac6a4b5e1616c3f3",
    "Bitmind": "0xda925c81137dd6e44891cdbd5e84bda3b4f81671",
    "AI Veronica": "0xb20f6f7d85f657c8cb66a7ee80799cf40f1d3533",
}

# Swap and Bridge Constants
KITE_BRIDGE_ROUTER_ADDRESS = "0x0BBB7293c08dE4e62137a557BC40bc12FA1897d6"
KITE_SWAP_ROUTER_ADDRESS = "0x04CfcA82fDf5F4210BC90f06C44EF25Bf743D556"
KITE_SWAP_FACTORY_ADDRESS = "0x147f235Dde1adcB00Ef8E2D10D98fEd9a091284D"
BRIDGE_ROUTER_ADDRESS = "0xD1bd49F60A6257dC96B3A040e6a1E17296A51375"

# Token Addresses
USDT_TOKEN_ADDRESS = "0x0fF5393387ad2f9f691FD6Fd28e07E3969e27e63"
WKITE_TOKEN_ADDRESS = "0x3bC8f037691Ce1d28c0bB224BD33563b49F99dE8"

# Bridge Configuration
DESTINATION_BLOCKCHAIN_ID = "0x6715950e0aad8a92efaade30bd427599e88c459c2d8e29ec350fc4bfb371a114"
BASE_SEPOLIA_CHAIN_ID = 84532

# Swap and Bridge ABI
SWAP_BRIDGE_ABI = [
    # Factory functions
    {
        "type": "function",
        "name": "factory",
        "stateMutability": "view",
        "inputs": [],
        "outputs": [{"name": "", "type": "address"}],
    },
    {
        "type": "function",
        "name": "getPair",
        "stateMutability": "view",
        "inputs": [
            {"name": "tokenA", "type": "address"},
            {"name": "tokenB", "type": "address"},
        ],
        "outputs": [{"name": "pair", "type": "address"}],
    },
    {
        "type": "function",
        "name": "allPairsLength",
        "stateMutability": "view",
        "inputs": [],
        "outputs": [{"name": "", "type": "uint256"}],
    },
    {
        "type": "function",
        "name": "getPool",
        "stateMutability": "view",
        "inputs": [
            {"name": "tokenA", "type": "address"},
            {"name": "tokenB", "type": "address"},
            {"name": "fee", "type": "uint24"},
        ],
        "outputs": [{"name": "pool", "type": "address"}],
    },
    # Pair functions
    {
        "type": "function",
        "name": "token0",
        "stateMutability": "view",
        "inputs": [],
        "outputs": [{"name": "", "type": "address"}],
    },
    {
        "type": "function",
        "name": "token1",
        "stateMutability": "view",
        "inputs": [],
        "outputs": [{"name": "", "type": "address"}],
    },
    {
        "type": "function",
        "name": "getReserves",
        "stateMutability": "view",
        "inputs": [],
        "outputs": [
            {"name": "reserve0", "type": "uint112"},
            {"name": "reserve1", "type": "uint112"},
            {"name": "blockTimestampLast", "type": "uint32"},
        ],
    },
    # Bridge functions
    {
        "type": "function",
        "name": "send",
        "stateMutability": "payable",
        "inputs": [
            {"name": "_destChainId", "type": "uint256"},
            {"name": "_recipient", "type": "address"},
            {"name": "_amount", "type": "uint256"},
        ],
        "outputs": [],
    },
    {
        "type": "function",
        "name": "initiate",
        "stateMutability": "payable",
        "inputs": [
            {"name": "token", "type": "address", "internalType": "address"},
            {"name": "amount", "type": "uint256", "internalType": "uint256"},
            {
                "name": "instructions",
                "type": "tuple",
                "internalType": "struct Instructions",
                "components": [
                    {"name": "sourceId", "type": "uint256", "internalType": "uint256"},
                    {"name": "receiver", "type": "address", "internalType": "address"},
                    {"name": "payableReceiver", "type": "bool", "internalType": "bool"},
                    {"name": "rollbackReceiver", "type": "address", "internalType": "address"},
                    {"name": "rollbackTeleporterFee", "type": "uint256", "internalType": "uint256"},
                    {"name": "rollbackGasLimit", "type": "uint256", "internalType": "uint256"},
                    {
                        "name": "hops",
                        "type": "tuple[]",
                        "internalType": "struct Hop[]",
                        "components": [
                            {"name": "action", "type": "uint8", "internalType": "enum Action"},
                            {"name": "requiredGasLimit", "type": "uint256", "internalType": "uint256"},
                            {"name": "recipientGasLimit", "type": "uint256", "internalType": "uint256"},
                            {"name": "trade", "type": "bytes", "internalType": "bytes"},
                            {
                                "name": "bridgePath",
                                "type": "tuple",
                                "internalType": "struct BridgePath",
                                "components": [
                                    {"name": "bridgeSourceChain", "type": "address", "internalType": "address"},
                                    {"name": "sourceBridgeIsNative", "type": "bool", "internalType": "bool"},
                                    {"name": "bridgeDestinationChain", "type": "address", "internalType": "address"},
                                    {"name": "cellDestinationChain", "type": "address", "internalType": "address"},
                                    {"name": "destinationBlockchainID", "type": "bytes32", "internalType": "bytes32"},
                                    {"name": "teleporterFee", "type": "uint256", "internalType": "uint256"},
                                    {"name": "secondaryTeleporterFee", "type": "uint256", "internalType": "uint256"},
                                ],
                            },
                        ],
                    },
                ],
            },
        ],
        "outputs": [],
    },
    # Standard ERC20 functions for token interactions
    {
        "type": "function",
        "name": "balanceOf",
        "stateMutability": "view",
        "inputs": [{"name": "account", "type": "address"}],
        "outputs": [{"name": "", "type": "uint256"}],
    },
    {
        "type": "function",
        "name": "approve",
        "stateMutability": "nonpayable",
        "inputs": [
            {"name": "spender", "type": "address"},
            {"name": "amount", "type": "uint256"},
        ],
        "outputs": [{"name": "", "type": "bool"}],
    },
    {
        "type": "function",
        "name": "allowance",
        "stateMutability": "view",
        "inputs": [
            {"name": "owner", "type": "address"},
            {"name": "spender", "type": "address"},
        ],
        "outputs": [{"name": "", "type": "uint256"}],
    },
]



class Agents:
    def __init__(self):
        self.agents = [
       {
            "agent": "Professor",
            "service": "deployment_KNmBm5VWg1HtB6AHXxX0vcyX",
            "questions": [
                "What’s the high-level vision of Kite AI?",
                "How does Kite AI’s Layer-1 coordinate computation and settlement?",
                "What are subnets in Kite AI and when should I use them?",
                "How do teams customize a subnet’s VM and gas policy?",
                "Which smart contract standards does Kite AI support (EVM, ERCs)?",
                "How does Proof of AI (PoAI) attribute contributions?",
                "Which on-chain events are recorded for PoAI receipts?",
                "How are data providers rewarded by PoAI?",
                "How can model creators monetize their models on Kite?",
                "What is an AI agent on Kite and how is it packaged?",
                "How do agents call each other or chain tools?",
                "How are agent inference requests billed?",
                "What is the role of the marketplace in Kite AI?",
                "What can be listed in the marketplace (models, agents, datasets)?",
                "How does Kite AI ensure fair revenue sharing?",
                "How are user data rights enforced on chain?",
                "Is model storage on-chain or off-chain, and why?",
                "How does Kite AI scale inference across subnets?",
                "What is the developer workflow to deploy an agent?",
                "Is there a public SDK for agents and models?",
                "How do I publish a dataset and define access controls?",
                "How are fine-tuning jobs tracked for attribution?",
                "What tokens are used in the Kite ecosystem?",
                "How are tokens earned through usage or contributions?",
                "Does Kite support staking and what are the rewards?",
                "How are network fees structured for L1 vs subnets?",
                "How does bridging work between Kite and Base Sepolia?",
                "Which routers are used for swap and bridge flows?",
                "How does the faucet work on testnet?",
                "How does Kite handle identity and smart accounts?",
                "Are account-abstraction wallets supported?",
                "How do gasless transactions work on Kite?",
                "What security audits exist for core contracts?",
                "How does governance work on Kite AI?",
                "Is there a grants program for builders?",
                "What are the main enterprise use cases for Kite?",
                "How can a company onboard private data safely?",
                "What anti-plagiarism protections exist for models?",
                "How are model licenses expressed and enforced?",
                "How do I integrate an external oracle or indexer?",
                "What metrics does the explorer show for agents and jobs?",
                "How does the daily quiz and XP system work?",
                "What is the receipt format for agent interactions?",
                "How are inference logs protected from leakage?",
                "Can I run a private subnet with allow-lists?",
                "What is the recommended dev environment and RPCs?",
                "How do I query balances and staking status via API?",
                "How does rollback/teleporter logic work in bridging?",
                "What is the ABI for initiating a cross-chain swap?",
                "How are upgrades to subnets and routers managed?",
                "How is validator performance measured?",
                "What is the roadmap for mainnet launch?",
                "How does Kite interoperate with Ethereum tooling?",
                "Are there sample agents or templates to start from?",
                "How do I test PoAI integration locally?",
                "What SLAs exist for hosted inference on Kite?",
                "How do I price an agent’s API calls?",
                "How does dispute resolution work for bad outputs?",
                "What privacy features protect user prompts?",
                "How do I submit a bridge transfer proof?",
                "How are caps or rate limits enforced for faucets?",
                "What are best practices for secure key management?",
                "How do I track rewards over time (dashboards/APIs)?",
                "What is the process to list an asset on the DEX?",
                "How are token decimals and metadata handled?",
                "How do I create and verify a PoAI receipt?",
                "What community channels exist for support?",
                "How do I contribute to protocol research?",
                "Which compliance standards does Kite target?",
                "How can I start building today—hello-world guide?",
                "How do I discover and install third-party agent modules?",
                "What’s the recommended pattern for long-running agent tasks?",
                "How do I sign and verify EIP-712 typed messages on Kite?",
                "Which entry point and paymaster patterns are supported for AA?",
                "How are bundlers and gas sponsorship set up for agents?",
                "How do I encode complex tuple arguments for router calls?",
                "What is destinationBlockchainID used for in bridge hops?",
                "How do I decode on-chain logs for agent inference receipts?",
                "What are best practices for retrying failed cross-chain calls?",
                "How do I monitor agent health and latency SLOs?",
                "How is rate limiting enforced for hostile/abusive clients?",
                "What observability hooks exist (events, webhooks, metrics)?",
                "How can I run local forks of the Kite testnet for dev?",
                "What is the recommended CI/CD for agent deployment?",
                "How do I create a subgraph (The Graph) for Kite events?",
                "What are common revert reasons in swap/bridge flows?",
                "How do I estimate gas reliably under congestion on Kite?",
                "How is maxPriorityFeePerGas handled on Kite L1 and subnets?",
                "What’s the difference between native and ERC-20 routes?",
                "How do I minimize MEV risk for agent-initiated swaps?",
                "How do I secure API keys and 2Captcha tokens in agents?",
                "How does the AA smart account derive and rotate keys?",
                "What’s the lifecycle of access tokens in Ozone API?",
                "How do I paginate and cache data from Ozone endpoints?",
                "How can I sandbox untrusted model code in an agent?",
                "What’s the recommended dataset versioning strategy?",
                "How are evaluation metrics for models stored and verified?",
                "How do I publish model cards with licensing metadata?",
                "How can I enable differential privacy for training jobs?",
                "Are there tools for red-teaming and bias audit of agents?",
                "How do I store large artifacts with content addressing?",
                "What’s the retention policy for inference logs and data?",
                "How can I implement usage-based billing for my agent?",
                "How do I validate marketplace purchases and entitlements?",
                "What’s the extension path for custom router actions?",
                "How do I use permit/permit2 to optimize approvals?",
                "What’s the pattern for meta-transactions on Kite?",
                "How do I recover from partial bridge execution (rollback)?",
                "How do I unit/integration test ABI encodings for hops?",
                "Which security pitfalls exist around bytes trade payloads?",
                "How do I compute price quotes using pool reserves on Kite?",
                "Is there a canonical price oracle or TWAP on Kite?",
                "How do I guard against re-entrancy in agent adapters?",
                "What’s the proper way to handle proxy rotation for RPC?",
                "How do I batch multiple agent actions atomically?",
                "How do I register and verify a custom subnet validator?",
                "What’s the governance process for protocol upgrades?",
                "How do I submit a KIP (Kite Improvement Proposal)?",
                "How can enterprises run private compliance-gated agents?",
                "What disaster recovery steps exist for lost keys?",
                "How do I export/import an agent including dependencies?",
                "How do I run performance benchmarks for my model on Kite?",
                "What are recommended logging formats for analytics?",
                "How can I stream responses (SSE) from agents to clients?",
                "How do I enforce per-user quotas and concurrency limits?",
                "What is the safest way to handle user-uploaded files?",
                "How do I localize agent prompts and UI content?",
                "How do I simulate faucet/XP flows in staging?",
                "What are examples of compliant data usage policies?",
                "How do I track end-to-end cost per inference request?",
                "How can I share private preview builds with testers?",
                "What’s the best practice for secrets in CI on Kite?",
                "How do I integrate hardware keys (Ledger, Trezor) for AA?",
                "How do I implement multi-sig controls for agent upgrades?",
                "What are example dashboards for KPIs (latency, cost, usage)?",
                "How do I create deterministic builds for agent containers?",
                "How do I publish a dataset with paid access tiers?",
                "How can I mirror models/weights between subnets safely?",
                "What is the process to deprecate or sunset an agent?",
                "How do I write a migration for router address changes?",
                "How can I expose a gRPC/HTTP endpoint to trigger agents?",
                "How do I validate user input to prevent prompt injection?",
                "What are the legal considerations for model licensing?",
                "How do I set up alerting for anomaly spikes and errors?",
                "How do I integrate an LLM guardrail or content filter?",
    "What’s the high-level vision of Kite AI?",
    "How does Kite AI’s Layer-1 coordinate computation and settlement?",
    "What are subnets in Kite AI and when should I use them?",
    "How do teams customize a subnet’s VM and gas policy?",
    "Which smart contract standards does Kite AI support?",
    "How does Proof of AI attribute contributions?",
    "Which on-chain events are recorded for PoAI receipts?",
    "How are data providers rewarded by PoAI?",
    "How can model creators monetize their models on Kite?",
    "What is an AI agent on Kite and how is it packaged?",
    "How do agents call each other or chain tools?",
    "How are agent inference requests billed?",
    "What is the role of the marketplace in Kite AI?",
    "What can be listed in the marketplace?",
    "How does Kite AI ensure fair revenue sharing?",
    "How are user data rights enforced on chain?",
    "Is model storage on-chain or off-chain and why?",
    "How does Kite AI scale inference across subnets?",
    "What is the developer workflow to deploy an agent?",
    "Is there a public SDK for agents and models?",
    "How do I publish a dataset and define access controls?",
    "How are fine-tuning jobs tracked for attribution?",
    "What tokens are used in the Kite ecosystem?",
    "How are tokens earned through usage or contributions?",
    "Does Kite support staking and what are the rewards?",
    "How are network fees structured for L1 vs subnets?",
    "How does bridging work between Kite and Base Sepolia?",
    "Which routers are used for swap and bridge flows?",
    "How does the faucet work on testnet?",
    "How does Kite handle identity and smart accounts?",
    "Are account-abstraction wallets supported?",
    "How do gasless transactions work on Kite?",
    "What security audits exist for core contracts?",
    "How does governance work on Kite AI?",
    "Is there a grants program for builders?",
    "What are the main enterprise use cases for Kite?",
    "How can a company onboard private data safely?",
    "What anti-plagiarism protections exist for models?",
    "How are model licenses expressed and enforced?",
    "How do I integrate an external oracle or indexer?",
    "What metrics does the explorer show for agents and jobs?",
    "How does the daily quiz and XP system work?",
    "What is the receipt format for agent interactions?",
    "How are inference logs protected from leakage?",
    "Can I run a private subnet with allow-lists?",
    "What is the recommended dev environment and RPCs?",
    "How do I query balances and staking status via API?",
    "How does rollback logic work in bridging?",
    "What is the ABI for initiating a cross-chain swap?",
    "How are upgrades to subnets and routers managed?",
    "How is validator performance measured?",
    "What is the roadmap for mainnet launch?",
    "How does Kite interoperate with Ethereum tooling?",
    "Are there sample agents or templates to start from?",
    "How do I test PoAI integration locally?",
    "What SLAs exist for hosted inference on Kite?",
    "How do I price an agent’s API calls?",
    "How does dispute resolution work for bad outputs?",
    "What privacy features protect user prompts?",
    "How do I submit a bridge transfer proof?",
    "How are faucet rate limits enforced?",
    "What are best practices for secure key management?",
    "How do I track rewards over time via APIs?",
    "What is the process to list an asset on the DEX?",
    "How are token decimals and metadata handled?",
    "How do I create and verify a PoAI receipt?",
    "What community channels exist for support?",
    "How do I contribute to protocol research?",
    "Which compliance standards does Kite target?",
    "How can I start building today with a hello-world?",
    "How do I discover and install third-party agent modules?",
    "What’s the recommended pattern for long-running agent tasks?",
    "How do I sign and verify EIP-712 typed messages on Kite?",
    "Which entry point and paymaster patterns are supported?",
    "How are bundlers and gas sponsorship set up for agents?",
    "How do I encode complex tuple arguments for router calls?",
    "What is destinationBlockchainID used for in bridge hops?",
    "How do I decode on-chain logs for inference receipts?",
    "What are best practices for retrying failed cross-chain calls?",
    "How do I monitor agent health and latency SLOs?",
    "How is rate limiting enforced for abusive clients?",
    "What observability hooks exist for events and metrics?",
    "How can I run local forks of the Kite testnet?",
    "What is the recommended CI/CD for agent deployment?",
    "How do I create a subgraph for Kite events?",
    "What are common revert reasons in swap flows?",
    "How do I estimate gas under congestion on Kite?",
    "How is maxPriorityFeePerGas handled on Kite?",
    "What’s the difference between native and ERC-20 routes?",
    "How do I minimize MEV risk for swaps?",
    "How do I secure API keys in agents?",
    "How does an AA smart account derive and rotate keys?",
    "What’s the lifecycle of access tokens in Ozone API?",
    "How do I paginate data from Ozone endpoints?",
    "How can I sandbox untrusted model code?",
    "What’s the recommended dataset versioning strategy?",
    "How are evaluation metrics for models verified?",
    "How do I publish model cards with metadata?",
    "How can I enable differential privacy in training?",
    "Are there tools for bias audit of agents?",
    "How do I store large artifacts with content addressing?",
    "What’s the retention policy for inference logs?",
    "How can I implement usage-based billing for agents?",
    "How do I validate marketplace entitlements?",
    "What’s the extension path for custom router actions?",
    "How do I use permit2 to optimize approvals?",
    "What’s the pattern for meta-transactions?",
    "How do I recover from partial bridge execution?",
    "How do I test ABI encodings for hops?",
    "Which pitfalls exist around bytes trade payloads?",
    "How do I compute price quotes using pool reserves?",
    "Is there a canonical price oracle on Kite?",
    "How do I guard against re-entrancy in adapters?",
    "What’s the proper way to handle proxy rotation?",
    "How do I batch multiple agent actions atomically?",
    "How do I register a custom subnet validator?",
    "What’s the governance process for upgrades?",
    "How do I submit a Kite Improvement Proposal?",
    "How can enterprises run private gated agents?",
    "What recovery steps exist for lost keys?",
    "How do I export and import an agent?",
    "How do I run performance benchmarks on Kite?",
    "What are recommended logging formats?",
    "How can I stream responses from agents?",
    "How do I enforce per-user concurrency limits?",
    "What is the safest way to handle uploaded files?",
    "How do I localize agent prompts and UI?",
    "How do I simulate faucet flows in staging?",
    "What are examples of data usage policies?",
    "How do I track cost per inference request?",
    "How can I share preview builds with testers?",
    "What’s the best practice for secrets in CI?",
    "How do I integrate hardware keys for AA?",
    "How do I implement multi-sig for upgrades?",
    "What dashboards show KPIs for agents?",
    "How do I create deterministic builds?",
    "How do I publish a dataset with paid tiers?",
    "How can I mirror models between subnets?",
    "What is the process to deprecate an agent?",
    "How do I write a migration for routers?",
    "How can I expose an HTTP endpoint for agents?",
    "How do I validate user input to prevent injection?",
    "What are legal considerations for licensing?",
    "How do I set up alerting for anomaly spikes?",
    "How do I integrate a content filter in agents?",
    "What are subnet validator hardware requirements?",
    "How do I verify block headers in a subnet?",
    "How do I fork and customize the Kite VM?",
    "What’s the lifecycle of a PoAI job?",
    "How do I measure energy cost of inference?",
    "How do I publish reproducible research on Kite?",
    "What incentives exist for early subnet validators?",
    "How do I connect Kite to IPFS or Arweave?",
    "What types of datasets are disallowed?",
    "How are toxic or unsafe prompts filtered?",
    "How do I whitelist contracts in a subnet?",
    "What benchmarks compare Kite to other AI chains?",
    "How do I report a vulnerability to Kite?",
    "What is the scope of the bug bounty program?",
    "How do I measure latency across subnets?",
    "How can I back up subnet state data?",
    "What’s the shard assignment logic in subnets?",
    "How do I join the Kite research community?",
    "How do I apply for the Kite fellowship?",
    "What workshops or hackathons are planned?",
    "How can I test my agent against adversarial inputs?",
    "What role do GPUs play in Kite validators?",
    "How do I provision compute for heavy models?",
    "Can I rent compute from third parties on Kite?",
    "How do I set price oracles for compute units?",
    "What is the dispute process for compute fraud?",
    "How are randomness beacons implemented?",
    "What’s the longest retention for XP records?",
    "How do I export XP history for a wallet?",
    "What is the format of NFT badges on Kite?",
    "How are badges linked to PoAI receipts?",
    "What are staking lockup periods on Kite?",
    "How do I unstake without penalties?",
    "What is the process to slash validators?",
    "How are subnet forks resolved?",
    "How do I measure subnet uptime?",
    "What’s the SLA for subnet operators?",
    "How do I join the Kite testnet as a validator?",
    "How do I request faucet tokens for testing?",
    "What explorer endpoints expose PoAI data?",
    "How do I check validator signatures?",
    "What is the process for contract upgrades?",
    "How do I migrate state between subnets?",
    "How do I pin a dataset for availability?",
    "What consensus does Kite use?",
    "How do I configure validator keys?",
    "What are minimum stake requirements?",
    "How is slashing enforced for downtime?",
    "How do I measure bandwidth for agents?",
    "What does the Kite CLI support?",
    "How do I deploy agents with Docker?",
    "How can I integrate Kite in Kubernetes?",
    "What is the Helm chart for Kite?",
    "How do I configure metrics scraping?",
    "How do I backtest PoAI rewards?",
    "What are inflation parameters for tokens?",
    "How do I apply for a subnet slot?",
    "What are subnet slot auction rules?",
    "How do I calculate subnet ROI?",
    "How can enterprises request private SLA?",
    "What integrations exist with SIWE?",
    "How do I connect Discord to Kite agents?",
    "What are the terms of service for Kite?",
    "How do I report abusive agents?",
    "How is censorship resistance ensured?",
    "What tools visualize PoAI contributions?",
    "How do I benchmark my agent against peers?",
    "How do I prove originality of my dataset?",
    "What is the escrow model in the marketplace?",
    "How do I protect trade secrets in models?",
    "What are examples of fair use in PoAI?",
    "How do I avoid leaking training data?",
    "How is key rotation enforced on Kite?",
    "What watchdogs detect unhealthy subnets?",
    "How can I run Kite on consumer hardware?",
    "What are best practices for subnet scaling?",
    "How is cross-subnet composability handled?",
    "What is the format of subnet genesis files?",
    "How do I test validator failover scenarios?",
    "How do I estimate subnet capacity?",
    "What tools audit subnet code?",
    "How do I fork a public agent into private use?",
    "What logging levels are recommended?",
    "How do I collect telemetry from my agent?",
    "How do I reduce latency for mobile clients?",
    "What UX guidelines exist for agent prompts?",
    "How do I monitor prompt abuse?",
    "How do I deploy canary versions of agents?",
    "What is the rollback process for agent upgrades?",
    "How do I benchmark end-to-end latency?",
    "What SDKs exist for mobile integration?",
    "How do I fetch subnet price feeds?",
    "How are gas tokens bridged across chains?",
    "What is the limit for faucet tokens per user?",
    "How do I prevent faucet sybil abuse?",
    "How do I enable subgraph indexing?",
    "What are best practices for prompt engineering?",
    "How do I integrate Kite agents with Slack?",
    "How do I unit test agent handlers?",
    "What rate limits apply to Ozone API?",
    "How do I debug agent crashes?",
    "What observability dashboards exist?",
    "How do I log PoAI receipts locally?",
    "What is the lifecycle of XP multipliers?",
    "How do I test governance proposals?",
    "How do I run localnet with multiple validators?",
    "What are recommended IDE extensions for Kite?",
    "How do I configure faucet distribution?",
    "What rate control exists for subnets?",
    "How do I monitor validator memory usage?",
    "What’s the optimal validator hardware?",
    "How do I run stress tests on Kite?",
    "How do I deploy subnet validators on cloud infrastructure?",
    "What’s the process for validator software upgrades?",
    "How are validator penalties broadcast on chain?",
    "How do I synchronize state between Kite and Ethereum?",
    "What fallback RPCs should I configure for reliability?",
    "How do I trace inference calls in subnet logs?",
    "How do I benchmark model throughput per GPU?",
    "What’s the minimal hardware spec for subnet validators?",
    "How do I handle validator disk growth over time?",
    "What replication options exist for state backups?",
    "How do I benchmark storage performance for Kite agents?",
    "How are token bridges secured against replay attacks?",
    "What is the canonical block explorer for Kite?",
    "How do I query historical XP data?",
    "How do I fetch validator slashing history?",
    "What’s the incentive for subnet collators?",
    "How do I visualize cross-subnet traffic?",
    "How do I store audit logs for compliance?",
    "How is GDPR compliance enforced for datasets?",
    "How do I redact sensitive data in logs?",
    "How do I rotate API keys automatically?",
    "What are subgraph caching strategies?",
    "How do I implement sharding in an agent?",
    "How do I benchmark subnet gossip latency?",
    "What metrics indicate validator misbehavior?",
    "How do I measure subnet finality times?",
    "What is the difference between PoAI and Proof of Work?",
    "How do I extend Kite SDK with custom modules?",
    "How can I run Kite with GPU passthrough in Docker?",
    "How do I measure gas cost per agent call?",
    "How do I calculate XP per dollar of compute?",
    "What licensing applies to open-source agents?",
    "How do I restrict marketplace access to regions?",
    "What’s the process for DMCA takedowns in Kite?",
    "How do I validate a subnet’s genesis hash?",
    "How do I secure subnet RPC endpoints?",
    "What TLS configs are required for validators?",
    "How do I handle validator key compromise?",
    "What is the rotation frequency for validator keys?",
    "How do I handle long-term dataset archiving?",
    "How do I verify data availability in subnets?",
    "How do I measure agent uptime objectively?",
    "What is the role of randomness in agent sampling?",
    "How do I enforce SLAs for hosted inference?",
    "What uptime guarantees exist for Kite RPCs?",
    "How can I stress test dataset queries?",
    "How do I write regression tests for agent outputs?",
    "How do I collect training metrics on Kite?",
    "What’s the cost structure for large dataset storage?",
    "How are subnet operators rewarded differently?",
    "What limits exist for agent package size?",
    "How do I check PoAI receipts in an explorer?",
    "How do I verify token transfers across bridges?",
    "How do I use Kite CLI for governance votes?",
    "What APIs expose validator health metrics?",
    "How can I simulate adversarial networks?",
    "How do I validate random number fairness?",
    "How do I simulate subnet forks locally?",
    "How do I migrate a dataset to a new subnet?",
    "How do I pin an agent to a subnet?",
    "What multi-region deployment options exist?",
    "How do I encrypt datasets in transit?",
    "How do I benchmark TLS overhead on Kite RPC?",
    "What metrics indicate PoAI efficiency?",
    "How do I integrate Kite into enterprise IAM?",
    "How do I federate identities across subnets?",
    "What methods exist for wallet recovery?",
    "How do I link DID to Kite accounts?",
    "How do I sandbox risky plugins in agents?",
    "What’s the best practice for plugin versioning?",
    "How do I run Kite in air-gapped environments?",
    "What monitoring is needed for subnet forks?",
    "How are governance votes weighted?",
    "What quorums are needed for upgrades?",
    "How do I dispute validator misbehavior?",
    "What evidence is required for slashing?",
    "How do I use multi-factor auth for Kite accounts?",
    "What is the lifecycle of faucet claims?",
    "How are faucet abuses detected?",
    "How do I request XP correction after error?",
    "What is the support process for agents?",
    "How do I whitelist enterprise wallets?",
    "What hardware HSMs integrate with Kite?",
    "How do I sign PoAI receipts offline?",
    "What integration exists with Ledger wallets?",
    "How do I integrate Kite in mobile apps?",
    "How do I sign meta-transactions on mobile?",
    "What’s the latency between Base and Kite?",
    "How do I bridge NFTs across Kite and Base?",
    "How are metadata preserved in NFT bridges?",
    "What is the retention of NFT provenance data?",
    "How do I build subgraphs for NFT trades?",
    "How do I detect spoofed NFT trades?",
    "What metrics define healthy agent adoption?",
    "How do I forecast agent revenues?",
    "How do I build dashboards for XP trends?",
    "What’s the long-term inflation schedule for KITE?",
    "How do I monitor emissions vs burn?",
    "What is the policy for token buybacks?",
    "How do I vote on inflation changes?",
    "How do I model KITE token velocity?",
    "What incentives exist for long-term staking?",
    "How do I model validator ROI in Kite?",
    "How are validator yields benchmarked?",
    "What metrics define validator quality?",
    "How do I run validator simulations?",
    "What logs indicate validator downtime?",
    "How do I replay subnet traffic for debugging?",
    "How do I replay agent prompts deterministically?",
    "What is the replay attack surface in PoAI?",
    "How do I store consent proofs on Kite?",
    "What is the retention for consent proofs?",
    "How do I enforce consent across subnets?",
    "How are cross-border data flows handled?",
    "How do I run load tests on Kite marketplace?",
    "What’s the max QPS per marketplace agent?",
    "How do I benchmark query response times?",
    "How do I compare Kite to other AI blockchains?",
    "What open research challenges exist in PoAI?",
    "How do I contribute to PoAI papers?",
    "What journals cite Kite research?",
    "What grants fund Kite research?",
    "How do I apply for academic access?",
    "How do I verify citations on Kite?",
    "What integrations exist with arXiv?",
    "How do I enforce embargoes on datasets?",
    "What legal remedies exist for IP theft?",
    "How do I challenge dataset authenticity?",
    "What arbitration mechanisms exist on Kite?",
    "How do I set up a dispute contract?",
    "What is the resolution timeline for disputes?",
    "How do I file evidence in disputes?",
    "How do I audit dispute outcomes?",
    "How do I use Kite DAO voting tools?",
    "How are DAO members identified?",
    "What credentials are used for DAO votes?",
    "How do I implement quadratic voting?",
    "What safeguards exist for DAO collusion?",
    "How do I fork Kite governance?",
    "What processes exist for hard forks?",
    "How do I coordinate chain upgrades?",
    "What’s the fallback if upgrade fails?",
    "How do I notify users of upgrades?",
    "How do I measure adoption of new features?",
    "How are backward compatibilities handled?",
    "What migration tools exist for upgrades?",
    "How do I document agent APIs?",
    "What schema formats are supported?",
    "How do I validate OpenAPI specs for agents?",
    "What tools lint agent schemas?",
    "How do I expose agent metrics as OpenTelemetry?",
    "How do I validate SLA adherence?",
    "What dashboards track SLA compliance?",
    "How do I escalate SLA breaches?",
    "What’s the governance around SLAs?",
    "How do I simulate SLA scenarios?",
    "How do I stress test SLA capacity?",
    "What are example SLAs for inference?",
    "How do I extend SLAs to datasets?",
    "How do I enforce SLAs in contracts?",
    "What monitoring confirms SLA delivery?",
    "How do I rotate SLA signers?",
    "How do I register SLA auditors?",
    "How do I verify SLA proofs?",
    "How do I monitor cross-chain XP flows?",
    "What events signal XP fraud?",
    "How do I mitigate XP fraud?",
    "What watchdogs monitor XP system?",
    "What governance rules apply to XP?",
    "How do I simulate XP multipliers?",
    "How do I stress test XP claims?",
    "What are edge cases for XP expiry?",
    "How do I monitor XP leaderboard fairness?",
    "What dashboards show XP history?",
    "How do I export XP data for research?",
    "How do I anonymize XP data?",
    "What legal standards govern XP?",
    "How do I enforce XP deletion requests?",
    "How do I prove XP attribution?",
    "What are examples of XP sybil attacks?",
    "How do I defend against XP sybil?",
    "What’s the cap for XP per wallet?",
    "How do I reset XP in errors?",
    "What is the XP audit frequency?",
    "How do I collect XP feedback?",
    "What role do XP play in staking?",
    "How do I model XP value in tokenomics?",
    "How do I visualize XP distribution?",
    "What metrics indicate XP abuse?",
    "How do I train models with XP-weighted data?",
    "How do I export XP for dashboards?",
    "How do I correlate XP with staking yields?",
    "What is the lifetime of XP badges?",
    "How are expired badges handled?",
    "How do I link XP badges to NFTs?",
    "How are XP badges displayed in explorers?",
    "What are incentives for XP badge holders?",
    "How do I prove badge authenticity?",
    "How do I prevent badge forgery?",
    "How do I expire badges automatically?",
    "What are common attacks on badges?",
    "How do I monitor badge adoption?",
    "What’s the max supply of badges?",
    "How are badge designs proposed?",
    "How do I mint badges for events?",
    "How do I test badge issuance?",
    "What governance rules apply to badges?",
    "How do I challenge invalid badges?",
    "What legal remedies exist for badges?",
    "How do I insure badge owners?",
    "How do I simulate badge loss?",
    "What are edge cases for badge transfers?",
    "How do I audit badge issuance?",
    "What watchdogs monitor badge system?",
    "What role do badges play in PoAI?",
    "How do I distribute badges fairly?",
    "How do I back up badge records?",
    "How do I mirror badge data?",
    "How do I visualize badge networks?",
    "What metrics indicate badge abuse?",
    "How do I stress test badge claims?",
    "What is the retention of badge logs?",
    "How do I export badge data?",
    "What legal rules apply to badges?",
    "How do I enforce badge deletions?",
    "How do I verify badge authenticity?",
    "How do I prove badge attribution?",
    "How do I anonymize badge data?",
    "How do I simulate badge multipliers?",
    "How do I train models with badge data?",
    "What is the XP badge audit cycle?",
    "How do I track badge leaderboard fairness?",
    "How do I link badges with staking?",
    "How do I measure badge ROI?",
    "How do I visualize badge usage?",
    "What incentives exist for badge issuers?",
    "How do I report badge abuse?",
    "How do I fork badge standards?",
    "What is the roadmap for badge upgrades?",
    ]
    },
    {
        "agent": "Crypto Buddy",
        "service": "deployment_xaYs98q4iraSThDSPcuPxZko",
        "questions": [
            "What’s the price of Bitcoin right now?",
            "How much did BTC move in the last 24h?",
            "What’s the current BTC dominance?",
            "What’s the ETH price and 24h volume?",
            "Which coins are the top movers today?",
            "What’s trending on Crypto Twitter right now?",
            "What is Worldcoin and how does it work?",
            "How does Worldcoin use biometric verification?",
            "Which exchanges list WLD and what’s its liquidity?",
            "What is Hyperliquid and who’s behind it?",
            "Is Hyperliquid L1 or L2 and how fast is it?",
            "Which tokens are actively traded on Hyperliquid?",
            "What is Injective Protocol (INJ)?",
            "Does Injective support spot, perp, or options?",
            "What is the utility of the INJ token?",
            "What’s the latest news around Injective?",
            "What is Jupiter (on Solana) and how to use it?",
            "Is Jupiter a DEX or an aggregator?",
            "Which tokens are hot on Jupiter today?",
            "How do Jupiter fees compare to other DEXs?",
            "What is Pepe (PEPE) and why is it popular?",
            "What are the risks of buying PEPE?",
            "Where can I trade PEPE with low slippage?",
            "Is PEPE listed on tier-1 exchanges?",
            "What is Bonk (BONK) and why is it popular on Solana?",
            "Is BONK inflationary or deflationary?",
            "Which wallets support BONK staking?",
            "Does BONK have real utility yet?",
            "What is FLOKI and what are its products?",
            "Is FLOKI connected to Elon’s dog meme?",
            "Where is FLOKI most liquid?",
            "Does FLOKI run a metaverse or game?",
            "What is Curve DAO and how does CRV work?",
            "How does Curve minimize slippage for stables?",
            "What’s CRV tokenomics and emissions?",
            "What happened to Curve’s TVL recently?",
            "Is Curve exposed to stablecoin depegs?",
            "What is the Artificial Superintelligence Alliance (ASI)?",
            "Which projects merged to form ASI?",
            "What’s the purpose of the ASI token?",
            "Who are major backers of ASI?",
            "What is Fartcoin and is it a joke token?",
            "On which chain does Fartcoin live?",
            "What was Fartcoin’s all-time high and low?",
            "Does Fartcoin have any community or utility?",
            "What are today’s gas fees on Ethereum?",
            "What are gas fees on Solana and Base right now?",
            "What’s the open interest on BTC perpetuals?",
            "What’s the funding rate for BTC/USDT?",
            "Which altcoins show unusual volume spikes?",
            "What are the top gainers and losers this week?",
            "What’s the total crypto market cap today?",
            "Are we in a risk-on or risk-off regime today?",
            "Any big token unlocks or cliffs this week?",
            "Which airdrops are rumored or ongoing?",
            "How do I bridge USDT from Ethereum to Kite?",
            "Where is KITE token tradable and what’s its price?",
            "How can I provide liquidity on a Kite DEX?",
            "What are current yields on major stablecoin pools?",
            "How do I stake tokens safely to avoid scams?",
            "What security tips reduce rug-pull risk?",
            "Which TA indicators suggest BTC trend direction?",
            "Where are key BTC support and resistance levels?",
            "Are there notable on-chain whale movements today?",
            "Any ETF inflow/outflow updates to watch?",
            "Which macro events could impact crypto this week?",
            "Which narratives are hot right now: AI, RWA, DePIN?",
            "Where to track new memecoin launches safely?",
            "How do I compare fees across DEX aggregators?",
            "What is the safest way to hold tokens long-term?",
            "How do DCA strategies work for BTC and ETH?",
            "What’s the difference between CEX and DEX custody risks?",
            "How do I calculate risk-adjusted returns (Sharpe/Sortino)?",
            "What tools help track a crypto portfolio over time?",
            "How do I hedge with perpetual futures effectively?",
            "What is basis trade and when is it profitable?",
            "How do options Greeks (delta, gamma) matter for BTC options?",
            "Where can I trade on-chain options safely?",
            "What are common liquidation risks on perps platforms?",
            "How does leverage impact drawdown and liquidation price?",
            "What is MEV and how does it affect swaps?",
            "How do I avoid sandwich attacks on AMMs?",
            "What is TWAP/VWAP and how to execute them on-chain?",
            "What are the risks of cross-chain bridges and how to mitigate?",
            "How do I revoke risky token approvals?",
            "How do I spot fake tokens and phishing sites?",
            "What is proof of reserves and does it matter for CEXs?",
            "How do stablecoins differ (USDC, USDT, DAI, FDUSD)?",
            "What’s real yield and where does it come from?",
            "What is LSDFi and how do stETH/rETH/eETH differ?",
            "What is restaking and how does EigenLayer work?",
            "What are LRTs and their main risks?",
            "How to use Aave/Compound/Morpho safely for yield?",
            "What is liquidation health factor and how to monitor it?",
            "How to analyze Uniswap V3 pools and set ranges?",
            "What is concentrated liquidity and impermanent loss?",
            "How do limit orders or hooks work on Uniswap V3?",
            "What’s the safest path to bridge to Base/Kite?",
            "How do I estimate slippage and price impact ahead of a swap?",
            "Which on-chain dashboards (Dune/DeFiLlama) should I follow?",
            "How to track token unlock schedules and supply inflation?",
            "What are typical scam patterns in Telegram/X groups?",
            "How do I secure seed phrases and hardware wallets?",
            "What’s the best practice for multisig treasury management?",
            "How do tax implications differ for trading vs staking?",
            "What is NFT floor price risk and liquidity risk?",
            "How to identify wash trading or spoofed volume?",
            "What’s the role of oracles and their failure modes?",
            "How to assess a project’s token distribution and vesting?",
            "What are good signals in a project’s GitHub activity?",
            "How to do basic on-chain forensics of a wallet?",
            "What is KYC/AML exposure when moving between CEX and DeFi?",
            "How to compare perps funding across venues quickly?",
            "How does volatility clustering affect trading strategies?",
            "What is a delta-neutral LP strategy and its risks?",
            "How to size positions to avoid overexposure?",
            "What’s the meaning of open interest spikes vs. price action?",
            "How to read orderbook depth and liquidity walls?",
            "How to evaluate collateral quality for lending protocols?",
            "What’s the risk of depegs for algorithmic stables?",
            "How to audit a token’s admin keys and upgradeability?",
            "What are signs of a potential governance attack?",
            "How to use on-chain alerts for whale or smart money flows?",
            "How to run a personal node or use trusted RPCs?",
            "What is gas token optimization across different L2s?",
            "How to ladder entries and exits to reduce slippage?",
            "What is a rebase token and how does it behave?",
            "How to evaluate emissions vs. real demand in yield farms?",
            "What is LVR (loss vs. rebalancing) for LPs?",
            "What are pre-confirmation risks and how to avoid them?",
            "How to identify reliable airdrop farming opportunities?",
            "What are best practices for storing airdropped tokens?",
            "How to avoid dusting attacks and malicious NFTs?",
            "What is perpetual DEX insurance fund and why it matters?",
            "How to detect unhealthy growth in a protocol’s TVL?",
            "What metrics predict liquidity crises in DeFi?",
            "How to use on-chain options for tail-risk hedging?",
            "What is cross-margin vs isolated margin and when to use each?",
            "How to trade narrative rotations without chasing tops?",
            "How to spot divergence between price and on-chain activity?",
            "How to evaluate bridges’ security postures (audits, bug bounties)?",
            "What is a safe checklist before interacting with a new dApp?",
            "How to use simulators to preview transaction outcomes?",
            "How to manage approvals with Permit/Permit2 securely?",
            "What is slippage tolerance and how to set it properly?",
            "How to read Etherscan/Kitescan tx details like a pro?",
            "How to spot hidden mint functions or dangerous proxies?",
            "What’s the price of Bitcoin right now?",
            "How much did BTC move in the last 24h?",
            "What’s the current BTC dominance?",
            "What’s the ETH price and 24h volume?",
            "Which coins are the top movers today?",
            "What’s trending on Crypto Twitter right now?",
            "What is Worldcoin and how does it work?",
            "How does Worldcoin use biometric verification?",
            "Which exchanges list WLD and what’s its liquidity?",
            "What is Hyperliquid and who’s behind it?",
            "Is Hyperliquid L1 or L2 and how fast is it?",
            "Which tokens are actively traded on Hyperliquid?",
            "What is Injective Protocol and what does it do?",
            "Does Injective support spot, perp, or options?",
            "What is the utility of the INJ token?",
            "What’s the latest news around Injective?",
            "What is Jupiter on Solana and how to use it?",
            "Is Jupiter a DEX or an aggregator?",
            "Which tokens are hot on Jupiter today?",
            "How do Jupiter fees compare to other DEXs?",
            "What is Pepe and why is it popular?",
            "What are the risks of buying PEPE?",
            "Where can I trade PEPE with low slippage?",
            "Is PEPE listed on tier-1 exchanges?",
            "What is Bonk and why is it popular on Solana?",
            "Is BONK inflationary or deflationary?",
            "Which wallets support BONK staking?",
            "Does BONK have real utility yet?",
            "What is FLOKI and what are its products?",
            "Is FLOKI connected to Elon’s dog meme?",
            "Where is FLOKI most liquid?",
            "Does FLOKI run a metaverse or game?",
            "What is Curve DAO and how does CRV work?",
            "How does Curve minimize slippage for stables?",
            "What’s CRV tokenomics and emissions?",
            "What happened to Curve’s TVL recently?",
            "Is Curve exposed to stablecoin depegs?",
            "What is the Artificial Superintelligence Alliance?",
            "Which projects merged to form ASI?",
            "What’s the purpose of the ASI token?",
            "Who are major backers of ASI?",
            "What is Fartcoin and is it a joke token?",
            "On which chain does Fartcoin live?",
            "What was Fartcoin’s all-time high and low?",
            "Does Fartcoin have any community or utility?",
            "What are today’s gas fees on Ethereum?",
            "What are gas fees on Solana and Base right now?",
            "What’s the open interest on BTC perpetuals?",
            "What’s the funding rate for BTC/USDT?",
            "Which altcoins show unusual volume spikes?",
            "What are the top gainers and losers this week?",
            "What’s the total crypto market cap today?",
            "Are we in a risk-on or risk-off regime today?",
            "Any big token unlocks or cliffs this week?",
            "Which airdrops are rumored or ongoing?",
            "How do I bridge USDT from Ethereum to Kite?",
            "Where is KITE token tradable and what’s its price?",
            "How can I provide liquidity on a Kite DEX?",
            "What are current yields on stablecoin pools?",
            "How do I stake tokens safely to avoid scams?",
            "What security tips reduce rug-pull risk?",
            "Which TA indicators suggest BTC trend direction?",
            "Where are key BTC support and resistance levels?",
            "Are there notable on-chain whale movements today?",
            "Any ETF inflow or outflow updates to watch?",
            "Which macro events could impact crypto this week?",
            "Which narratives are hot right now in crypto?",
            "Where to track new memecoin launches safely?",
            "How do I compare fees across DEX aggregators?",
            "What is the safest way to hold tokens long-term?",
            "How do DCA strategies work for BTC and ETH?",
            "What’s the difference between CEX and DEX custody risks?",
            "How do I calculate risk-adjusted returns?",
            "What tools help track a crypto portfolio?",
            "How do I hedge with perpetual futures?",
            "What is basis trade and when is it profitable?",
            "How do options Greeks matter for BTC options?",
            "Where can I trade on-chain options safely?",
            "What are common liquidation risks on perps?",
            "How does leverage impact liquidation price?",
            "What is MEV and how does it affect swaps?",
            "How do I avoid sandwich attacks on AMMs?",
            "What is TWAP and VWAP in crypto trading?",
            "What are risks of cross-chain bridges?",
            "How do I revoke risky token approvals?",
            "How do I spot fake tokens and phishing sites?",
            "What is proof of reserves and why is it important?",
            "How do stablecoins differ in design?",
            "What’s real yield and where does it come from?",
            "What is LSDFi and how do stETH and rETH differ?",
            "What is restaking and how does EigenLayer work?",
            "What are LRTs and their main risks?",
            "How do I use Aave or Compound safely?",
            "What is liquidation health factor?",
            "How to analyze Uniswap V3 pools and set ranges?",
            "What is concentrated liquidity and its risks?",
            "How do limit orders work on Uniswap V3?",
            "What’s the safest path to bridge to Base or Kite?",
            "How do I estimate slippage before a swap?",
            "Which dashboards track DeFi metrics?",
            "How to track token unlock schedules?",
            "What are common scam patterns in crypto groups?",
            "How do I secure seed phrases safely?",
            "What’s best practice for multisig treasuries?",
            "How do tax implications differ for trading vs staking?",
            "What is NFT floor price risk?",
            "How to identify wash trading in NFTs?",
            "What’s the role of oracles in DeFi?",
            "How to assess a project’s token distribution?",
            "What are signals in a project’s GitHub activity?",
            "How to do basic on-chain forensics of a wallet?",
            "What is KYC/AML exposure in DeFi?",
            "How to compare funding rates across exchanges?",
            "How does volatility clustering affect trading?",
            "What is a delta-neutral LP strategy?",
            "How to size positions to avoid overexposure?",
            "What’s the meaning of open interest spikes?",
            "How to read orderbook depth in crypto?",
            "How to evaluate collateral quality in lending?",
            "What’s the risk of depegs in stablecoins?",
            "How to audit token admin keys?",
            "What are signs of a governance attack?",
            "How to use on-chain alerts for whales?",
            "How to run a personal node for safety?",
            "What is gas optimization across L2s?",
            "How to ladder entries and exits?",
            "What is a rebase token and how does it work?",
            "How to evaluate emissions in yield farms?",
            "What is LVR in liquidity pools?",
            "What are pre-confirmation risks?",
            "How to identify reliable airdrops?",
            "What are best practices for storing airdrops?",
            "How to avoid dusting attacks?",
            "What is an insurance fund on perps DEX?",
            "How to detect unhealthy TVL growth?",
            "What metrics predict liquidity crises?",
            "How to use on-chain options for hedging?",
            "What is cross-margin vs isolated margin?",
            "How to trade narrative rotations?",
            "How to spot divergence in on-chain data?",
            "How to evaluate bridge security?",
            "What is a checklist before using new dApps?",
            "How to preview transaction outcomes safely?",
            "How to manage approvals securely?",
            "What is slippage tolerance in swaps?",
            "How to read Etherscan transactions?",
            "How to spot hidden mint functions?",
            "What is the safest way to store NFTs?",
            "How do NFT royalties work on chain?",
            "What’s the impact of Blur on NFT markets?",
            "How to evaluate NFT communities?",
            "What is floor sweeping and its risks?",
            "How do NFT loans and rentals work?",
            "What are risks of NFT lending platforms?",
            "What is fractionalized NFT ownership?",
            "How to assess NFT liquidity depth?",
            "What is the role of marketplaces in NFT discovery?",
            "How do I avoid scams in NFT airdrops?",
            "What are top NFT analytics tools?",
            "What is wash trading in NFT markets?",
            "How to verify rarity traits in NFTs?",
            "What metrics track NFT adoption?",
            "How do royalties affect NFT supply?",
            "What is cross-chain NFT bridging?",
            "How to secure NFT metadata storage?",
            "What are risks of off-chain NFT metadata?",
            "How to ensure NFT authenticity?",
            "How do I evaluate NFT staking rewards?",
            "What is gamified staking in NFTs?",
            "How do dynamic NFTs work?",
            "What are examples of NFT utility?",
            "What risks exist with NFT marketplaces?",
            "How to detect NFT pump and dumps?",
            "What is NFT wash loan abuse?",
            "What is the safest NFT custody method?",
            "How to track blue-chip NFT sales?",
            "What are signs of NFT market manipulation?",
            "How to value rare NFTs fairly?",
            "What NFT lending protocols exist?",
            "How to avoid scams in NFT Discords?",
            "What are NFT rug pulls?",
            "How to spot fake NFT collections?",
            "What NFT indexes or ETFs exist?",
            "How to tax NFTs in different countries?",
            "What NFT insurance exists?",
            "How do NFT DAOs function?",
            "How do I participate in NFT governance?",
            "What’s the future of NFT standards?",
            "How are NFTs evolving with AI?",
            "What is the overlap of NFTs and DeFi?",
            "How are NFTs used in gaming?",
            "What are risks in NFT gaming economies?",
            "What are NFT derivatives?",
            "What’s the liquidity premium for NFTs?",
            "How are NFTs used as collateral?",
            "What NFT-backed loans exist?",
            "How to monitor NFT flash loan abuse?",
            "What NFT oracle risks exist?",
            "What NFT bridges exist?",
            "How to prevent NFT metadata loss?",
            "What NFT recovery options exist?",
            "What metrics show NFT hype cycles?",
            "How to spot NFT influencers’ shills?",
            "What NFT wash trading signals exist?",
            "What are NFT lockups and vesting?",
            "What NFT exit scams exist?",
            "What metrics show NFT liquidity health?",
            "How do NFT raffles work?",
            "What are NFT launchpad risks?",
            "How to secure NFT minting sites?",
            "What NFT custodians exist?",
            "What NFT protocols are audited?",
            "How to secure NFT smart contracts?",
            "How do I identify scam NFT websites?",
            "What are NFT airdrop farming risks?",
            "How do NFT staking yields compare?",
            "What NFT indexes track blue chips?",
            "What NFT derivatives are emerging?",
            "How to avoid phishing in NFT mints?",
            "What are NFT community risks?",
            "How do I DYOR for NFTs?",
            "What NFT regulation exists?",
            "How to report NFT fraud?",
            "What NFT governance tokens exist?",
            "How do NFT voting systems work?",
            "What are NFT royalties disputes?",
            "How are NFT royalty fees enforced?",
            "What’s the trend for NFT royalties?",
            "What metrics show NFT social adoption?",
            "How to analyze NFT sentiment on Twitter?",
            "What NFT scams use fake influencers?",
            "What are NFT escrow services?",
            "How do NFT rentals function?",
            "What are NFT staking lockups?",
            "What NFT gaming risks exist?",
            "How do NFT marketplaces compete?",
            "What are NFT aggregator risks?",
            "How do NFT floor sweeps impact markets?",
            "What NFT wash trade metrics exist?",
            "How to evaluate NFT lending health?",
            "What NFT risks exist in bridges?",
            "How are NFT royalties gamed?",
            "What NFT minting risks exist?",
            "What NFT staking abuse cases exist?",
            "What NFT adoption metrics matter?",
            "What NFT liquidity pools exist?",
            "How to use NFTs for collateral safely?",
            "What NFT flash loan risks exist?",
            "What NFT arbitrage exists?",
            "How do NFT indexes hedge risk?",
            "What NFT DAOs govern collections?",
            "What NFT regulation risks exist?",
            "How do NFT rug pulls happen?",
            "What NFT wash trade detection tools exist?",
            "What NFT tracking dashboards exist?",
            "What NFT scams repeat often?",
            "What NFT custody risks exist?",
            "What NFT staking lock risks exist?",
            "What NFT insurance protocols exist?",
            "What NFT influencer abuses exist?",
            "What NFT rating systems exist?",
            "What NFT launchpad models exist?",
            "What NFT mint taxonomies exist?",
            "How are NFTs integrated into DeFi?",
            "What NFT gaming tokenomics exist?",
            "What NFT derivatives trade on-chain?",
            "How are NFTs used in DAOs?",
            "What NFT governance abuses exist?",
            "What NFT royalty debates exist?",
            "How do NFT wash loans work?",
            "What NFT flash crash risks exist?",
            "How to avoid NFT phishing emails?",
            "What NFT security checklists exist?",
            "What NFT rug detection methods exist?",
            "What NFT regulation challenges exist?",
            "How do NFT DAOs raise capital?",
            "What NFT scam case studies exist?",
            "How to audit NFT contracts?",
            "What NFT bridges are safest?",
            "What NFT airdrops are legit?",
            "What NFT valuation models exist?",
            "How to measure NFT social reach?",
            "What NFT hype metrics matter?",
            "What NFT scams target Discord?",
            "What NFT minting audits exist?",
            "What NFT staking protocols exist?",
            "How to prevent NFT metadata rug pulls?",
            "What NFT recovery cases exist?",
            "How to monitor NFT derivatives?",
            "What NFT valuation tools exist?",
            "How do NFT flash loans impact markets?",
            "What NFT wash trading regulations exist?",
            "How do NFT DAOs share profits?",
            "What NFT launch metrics matter?",
            "How to detect NFT bot mints?",
            "What NFT community metrics exist?",
            "What NFT scam watchlists exist?",
            "How do NFT custody solutions compare?",
            "What NFT fraud insurance exists?",
            "How do NFT oracles work?",
            "What NFT derivative risks exist?",
            "How to analyze NFT vesting schedules?",
            "What NFT DAO voting metrics exist?",
            "What NFT royalty evasion cases exist?",
            "What NFT market manipulation risks exist?",
            "What NFT audit standards exist?",
            "How do NFT derivatives hedge exposure?",
            "What NFT bridges carry most risk?",
            "How do NFT staking pools compare?",
            "What NFT aggregator benefits exist?",
            "What NFT governance debates exist?",
            "How to measure NFT liquidity ratios?",
            "What NFT rug pull signs exist?",
            "How to secure NFT wallets?",
            "What NFT hype indicators exist?",
            "What NFT scam bots exist?",
            "What NFT mint insurance exists?",
            "What NFT custody providers exist?",
            "What NFT airdrop safety tips exist?",
            "What NFT DAO risks exist?",
            "What NFT regulation trends exist?",
            "What NFT scam prevention tools exist?",
            "What NFT derivatives indexes exist?",
            "What NFT lending abuses exist?",
            "How to avoid NFT Discord scams?",
            "What NFT social adoption patterns exist?",
            "How do NFT liquidity pools function?",
            "What NFT gaming risks repeat?",
            "How do NFT launchpads manage risk?",
            "What NFT governance protections exist?",
            "What NFT royalty sharing risks exist?",
            "What NFT aggregator scams exist?",
            "What NFT hype tracking tools exist?",
            "What NFT regulation case studies exist?",
            "What NFT insurance cases exist?",
            "What NFT DAO misuses exist?",
            "What NFT scam audits exist?",
            "How to prevent NFT wash trading?",
            "What NFT derivative tracking exists?",
            "What NFT fraud metrics exist?",
            "What NFT mint scams exist?",
            "What NFT valuation abuses exist?",
            "What NFT hype abuses exist?",
            "What NFT rug pull metrics exist?",
            "How to secure NFT DAOs?",
            "What NFT phishing metrics exist?",
            "What NFT aggregator audits exist?",
            "What NFT governance flaws exist?",
            "What NFT royalty metrics matter?",
            "What NFT scams target Twitter?",
            "What NFT airdrop risks repeat?",
            "What NFT launch risks exist?",
            "How to detect NFT governance capture?",
            "What NFT liquidity abuses exist?",
            "What NFT hype cycles repeat?",
            "What NFT fraud trackers exist?",
            "What NFT DAO models exist?",
            "What NFT regulation loopholes exist?",
            "How do NFT flash loans exploit markets?",
            "What NFT social signals predict hype?",
            "How do stablecoin yields compare across protocols?",
            "What are the risks of algorithmic stablecoins?",
            "How do CBDCs impact crypto adoption?",
            "What are the pros and cons of tokenized treasuries?",
            "How does RWA tokenization work in practice?",
            "What are leading RWA projects today?",
            "How to evaluate RWA token yield safety?",
            "What are risks in tokenized bonds?",
            "How to assess RWA collateral chains?",
            "What role do custodians play in RWA tokens?",
            "How to audit RWA smart contracts?",
            "What legal issues exist for RWAs?",
            "How do RWAs interact with DeFi?",
            "What are examples of RWA hacks?",
            "What is the future of RWA regulation?",
            "How to value tokenized real estate?",
            "What are risks of real estate tokenization?",
            "How to evaluate tokenized carbon credits?",
            "What is the liquidity risk in RWAs?",
            "What are custody challenges in RWAs?",
            "How to assess oracle risk in RWAs?",
            "What are leading DePIN projects?",
            "How does Helium’s token model work?",
            "What is Filecoin’s current role in DePIN?",
            "What are risks in DePIN supply models?",
            "How to assess demand in DePIN tokens?",
            "What are real-world use cases of DePIN?",
            "How to monitor DePIN growth?",
            "What metrics matter in DePIN adoption?",
            "What are risks of over-centralization in DePIN?",
            "How does DePIN token inflation work?",
            "What are leading AI + Crypto projects?",
            "How do AI tokens differ from other utility tokens?",
            "What’s the role of compute marketplaces in AI tokens?",
            "How do I value AI agents in token models?",
            "What are risks of AI model tokenization?",
            "How to monitor AI token adoption?",
            "What are key AI token governance debates?",
            "How do AI chains compete with Kite AI?",
            "What are examples of AI compute token failures?",
            "How do I assess AI token liquidity?",
            "What is the overlap of AI and DeFi?",
            "What is the overlap of AI and NFTs?",
            "How do AI projects attract liquidity?",
            "What risks exist in AI project hype?",
            "What metrics track AI adoption?",
            "What are leading meme coins now?",
            "How to assess meme coin sustainability?",
            "What metrics predict meme coin collapse?",
            "What is the psychology behind meme coins?",
            "What risks are common in meme coin trading?",
            "How to track meme coin whales?",
            "What meme coin launchpads exist?",
            "How do I avoid scams in meme coins?",
            "What tools help track meme coin trends?",
            "How to hedge meme coin exposure?",
            "What are examples of meme coin failures?",
            "How to audit meme coin contracts?",
            "What meme coin governance models exist?",
            "What is the lifecycle of meme coin hype?",
            "How do I value meme coins objectively?",
            "What is the safest way to farm meme coins?",
            "What NFT + meme coin hybrids exist?",
            "How do meme coins pump and dump?",
            "What regulatory risks face meme coins?",
            "What are meme coin airdrop models?",
            "How do I avoid meme coin rug pulls?",
            "What meme coin exchanges list safely?",
            "What meme coin arbitrage exists?",
            "What meme coin derivatives exist?",
            "How to track meme coin unlock schedules?",
            "What meme coin custody risks exist?",
            "What meme coin influencers to avoid?",
            "How to detect meme coin scams?",
            "What metrics signal meme coin exits?",
            "What meme coin DAOs exist?",
            "What meme coin staking yields exist?",
            "How do meme coins integrate with DeFi?",
            "What meme coin launch metrics matter?",
            "How to measure meme coin liquidity?",
            "What meme coin oracles exist?",
            "What meme coin wash trading risks exist?",
            "How do meme coin bots manipulate markets?",
            "What meme coin regulations are proposed?",
            "What meme coin hype metrics matter?",
            "How to spot meme coin influencer scams?",
            "What meme coin recovery cases exist?",
            "How to tax meme coin profits?",
            "What meme coin sentiment tools exist?",
            "What meme coin community risks exist?",
            "How do meme coin derivatives hedge risk?",
            "What meme coin tracking dashboards exist?",
            "What meme coin lending protocols exist?",
            "What meme coin scam watchlists exist?",
            "How to value meme coin NFTs?",
            "What meme coin adoption metrics exist?",
            "What meme coin hype cycles repeat?",
            "What meme coin liquidity ratios matter?",
            "What meme coin exit scams exist?",
            "What meme coin governance abuses exist?",
            "What meme coin scam audits exist?",
            "How to prevent meme coin phishing?",
            "What meme coin aggregator risks exist?",
            "How to avoid meme coin Discord scams?",
            "What meme coin flash loan abuses exist?",
            "What meme coin flash crash risks exist?",
            "How do meme coin DAOs mismanage funds?",
            "What meme coin royalty scams exist?",
            "How to detect meme coin wash trading?",
            "What meme coin DAO models exist?",
            "What meme coin scam bots exist?",
            "What meme coin hype abuses exist?",
            "What meme coin custody providers exist?",
            "What meme coin insurance exists?",
            "What meme coin influencers manipulate markets?",
            "What meme coin oracles risks exist?",
            "What meme coin mint scams exist?",
            "What meme coin valuation tools exist?",
            "What meme coin rug metrics exist?",
            "What meme coin liquidity pools exist?",
            "How do meme coin flash loans impact prices?",
            "What meme coin DAO protections exist?",
            "What meme coin governance debates exist?",
            "How do meme coin DAOs share profits?",
            "What meme coin hype tracking tools exist?",
            "What meme coin fraud insurance exists?",
            "How do meme coin indexes hedge exposure?",
            "What meme coin lending abuses exist?",
            "How do meme coin rug pulls repeat?",
            "What meme coin scam trackers exist?",
            "What meme coin regulation loopholes exist?",
            "What meme coin flash crash metrics exist?",
            "What meme coin sentiment abuses exist?",
            "How to measure meme coin ROI?",
            "What meme coin hype cycles predict?",
            "What meme coin fraud cases exist?",
            "What meme coin wash trade metrics exist?",
            "What meme coin scam prevention tools exist?",
            "What meme coin launch risks exist?",
            "What meme coin scam case studies exist?",
            "How do meme coin DAOs capture governance?",
            "What meme coin fraud audits exist?",
            "How do meme coin whales exploit markets?",
            "What meme coin oracles audits exist?",
            "How do meme coin derivatives manipulate markets?",
            "What meme coin DAO voting metrics exist?",
            "What meme coin hype manipulation exists?",
            "What meme coin tax loopholes exist?",
            "How do meme coin wash loans work?",
            "What meme coin scam bots repeat?",
            "What meme coin exit strategies exist?",
            "What meme coin governance flaws exist?",
            "What meme coin recovery tools exist?",
            "What meme coin hype indicators exist?",
            "What meme coin liquidity abuses exist?",
            "How do meme coin regulations evolve?",
            "What meme coin valuation abuses exist?",
            "What meme coin scam audits repeat?",
            "How to avoid meme coin phishing emails?",
            "What meme coin hype ratios exist?",
            "How to detect meme coin bot mints?",
            "What meme coin fraud trackers exist?",
            "How do meme coin DAOs abuse funds?",
            "What meme coin scam case laws exist?",
            "What meme coin hype trackers exist?",
            "What meme coin liquidity trackers exist?",
            "How to secure meme coin wallets?",
            "What meme coin insurance protocols exist?",
            "What meme coin recovery metrics exist?",
            "How do meme coin DAOs raise capital?",
            "What meme coin sentiment ratios exist?",
            "What meme coin social metrics exist?",
            "What meme coin hype cycles abuse exist?",
            "What meme coin scam rating systems exist?",
            "What meme coin launchpad risks exist?",
            "What meme coin mint audits exist?",
            "How do meme coin aggregators compete?",
            "What meme coin derivatives indexes exist?",
            "What meme coin hype indicators repeat?",
            "What meme coin fraud metrics exist?",
            "What meme coin flash loans risks exist?",
            "What meme coin scam detection tools exist?",
            "What meme coin governance protections exist?",
            "How to evaluate meme coin liquidity pools?",
            "What meme coin market manipulation exists?",
            "What meme coin community abuses exist?",
            "What meme coin hype trackers repeat?",
            "What meme coin scam watchlists repeat?",
            "How to hedge meme coin yield farming?",
            "What meme coin hype frauds exist?",
            "What meme coin sentiment trackers exist?",
            "What meme coin regulation proposals exist?",
            "How to avoid meme coin influencer scams?",
            "What meme coin wash trade detection exists?",
            "What meme coin valuation trackers exist?",
            "What meme coin scam prevention audits exist?",
            "What meme coin liquidity protection exists?",
            "What meme coin hype detection exists?",
            "What meme coin custody audits exist?",
            "What meme coin ROI tools exist?",
            "What meme coin derivatives abuses exist?",
            "How do meme coin wash trades impact markets?",
            "What meme coin hype risks exist?",
            "What meme coin exit audits exist?",
            "How to audit meme coin DAOs?",
            "What meme coin regulation metrics exist?",
            "What meme coin insurance metrics exist?",
            "What meme coin fraud trackers repeat?",
            "What meme coin scam detection audits exist?",
            "What meme coin hype trackers exist?",
            "What meme coin valuation ratios exist?",
            "What meme coin liquidity metrics exist?",
            "What meme coin tax abuses exist?",
            "How to protect meme coin DAOs?",
            "What meme coin governance ratings exist?",
            "What meme coin hype cycles metrics exist?",
            "What meme coin scam ratings exist?",
            "How do meme coin derivatives hedge risk?",
            "What meme coin DAO frauds exist?",
            "What meme coin hype prediction tools exist?",
            "What meme coin scam protection tools exist?",
            "What meme coin valuation audits exist?",
            "What meme coin liquidity abuses repeat?",
            "What meme coin recovery audits exist?",
            "What meme coin hype manipulation tools exist?",
            "What meme coin sentiment audits exist?",
            "What meme coin insurance abuses exist?",
            "What meme coin regulation frauds exist?",
            "How do meme coin aggregators exploit users?",
            "What meme coin scam prevention exists?",
            "How to audit meme coin governance?",
            "What meme coin valuation scams exist?",
            "What meme coin hype ROI exist?",
            "What meme coin liquidity trackers repeat?",
            "What meme coin fraud audits exist?",
            "What meme coin insurance trackers exist?",
            "What meme coin scam frauds exist?",
            "How to prevent meme coin phishing scams?",
            "What meme coin sentiment frauds exist?",
            "What meme coin hype rating systems exist?",
            "How to tax meme coin staking rewards?",
            "What meme coin community trackers exist?",
            "What meme coin hype scams exist?",
            "What meme coin liquidity frauds exist?",
            "What meme coin regulation trackers exist?",
            "What meme coin scam trackers repeat?",
            "How do meme coin DAOs misuse funds?",
            "What meme coin fraud prevention exist?",
            "What meme coin hype trackers abuse exist?",
            "How to measure meme coin adoption metrics?",
            "What meme coin hype prediction exist?",
            "What meme coin insurance frauds exist?",
            "What meme coin scam audits exist?",
            "How to prevent meme coin rug pulls?",
            "What meme coin sentiment trackers repeat?",
            "What meme coin recovery scams exist?",
            "How to detect meme coin fraud signals?",
            "What meme coin hype case studies exist?",
            "What meme coin tax trackers exist?",
            "What meme coin liquidity protection tools exist?",
            "What meme coin valuation trackers repeat?",
            "What meme coin ROI audits exist?",
            "What meme coin scam prediction tools exist?",
            "How do meme coin aggregators abuse fees?",
            "What meme coin hype trackers abuse exist?",
            "What meme coin fraud metrics repeat?",
            "What meme coin governance audits exist?",
            "What meme coin scam ratings repeat?",
            "What meme coin hype ROI tools exist?",
            "What meme coin liquidity ratings exist?",
            "How to detect meme coin scams early?",
            "What meme coin valuation metrics repeat?",
            "What meme coin regulation audits exist?",
            "What meme coin hype signals exist?",
            "What meme coin tax protection exist?",
            "What meme coin fraud predictions exist?",
            "What meme coin scam audits repeat?",
            "How do meme coin DAOs raise scams?",
            "What meme coin hype protection exist?",
            "What meme coin liquidity ratios repeat?",
            "What meme coin scam predictions exist?",
            "What meme coin valuation frauds exist?",
            "How to secure meme coin DAOs?",
            "What meme coin sentiment ratios repeat?",
            "What meme coin hype trackers fraud exist?",
            "What meme coin insurance ratings exist?",
            "What meme coin scam cycles exist?",
            "What meme coin hype fraud ratios exist?",
            "What meme coin regulation predictions exist?",
            "What meme coin governance frauds exist?",
            "What meme coin hype trackers repeat exist?",
            "How to hedge meme coin volatility?",
            "What meme coin fraud trackers abuse exist?",
            "What meme coin scam audits protection exist?",
            "What meme coin liquidity audits exist?",
            "What meme coin hype trackers prediction exist?",
            "What meme coin insurance trackers repeat exist?",
            "What meme coin ROI predictions exist?",
            "How to prevent meme coin scams repeat?"
        ]
    },
    {
        "agent": "Sherlock",
        "service": "deployment_15kFpEbiREAocsWpSxbGATAr",
        "questions": [
            "What do you think of this transaction?",
            "Do you see anything suspicious in this tx hash?",
            "Decode the calldata and explain what this tx does.",
            "Which function is being called and on which contract?",
            "Break down token flows: what moves where and how much?",
            "Does this transaction grant any approvals or infinite allowances?",
            "Is this a swap, a bridge, or something else?",
            "Identify all contracts and EOAs touched by this tx.",
            "Estimate the gas usage and fees—does it look reasonable?",
            "Are there hidden permissions or delegatecall patterns?",
            "What do you think of this transaction?",
            "Do you see anything suspicious in this tx hash?",
            "Decode the calldata and explain what this tx does.",
            "Which function is being called and on which contract?",
            "Break down token flows: what moves where and how much?",
            "Does this transaction grant any approvals or infinite allowances?",
            "Is this a swap, a bridge, or something else?",
            "Identify all contracts and EOAs touched by this tx.",
            "Estimate the gas usage and fees—does it look reasonable?",
            "Are there hidden permissions or delegatecall patterns?",
            "Does this transaction interact with a known malicious contract?",
            "Are there reentrancy risks in this transaction flow?",
            "Does this tx trigger selfdestruct or contract creation?",
            "Which protocols or dApps are involved here?",
            "Does this look like a flashloan attack setup?",
            "Are there nested calls that hide actual intent?",
            "What approvals are changed in this transaction?",
            "Does this interact with proxy contracts?",
            "Can this tx drain funds if repeated?",
            "Is this transaction frontrunnable?",
            "Does the calldata encode suspicious opcodes?",
            "Are there abnormal gas limits or gas prices?",
            "Does this transaction use Permit or Permit2?",
            "Could this tx bypass slippage protections?",
            "Is there any approval of unlimited tokens?",
            "Does this interact with a known bridge?",
            "Which tokens are transferred and in what amounts?",
            "Are funds sent to a mixer or anonymizer?",
            "Is this transaction exploiting a MEV opportunity?",
            "Does this include a multicall batch?",
            "Which contracts are proxies and which are logic?",
            "Are there delegatecalls to unknown contracts?",
            "Does this transaction match common exploit patterns?",
            "Are approvals revoked or only added?",
            "Does this transaction mint or burn tokens?",
            "What risks does this transaction pose to the sender?",
            "Does this involve governance contracts?",
            "Are funds moved between chains?",
            "Does this transaction upgrade a proxy contract?",
            "Could this tx drain a liquidity pool?",
            "Is this a sandwich attack attempt?",
            "Does this interact with a compromised private key?",
            "Are any NFTs transferred here?",
            "Is this an approve-and-call combo?",
            "Does this transaction manipulate an oracle?",
            "Which wallets benefit most from this transaction?",
            "Is this tx consistent with normal user behavior?",
            "Does this transaction match phishing patterns?",
            "Is the contract verified or unverified on chain?",
            "Does this include suspicious fallback functions?"
        ]
    }
]